//mod print;
//mod variables;
// mod string;
// mod types;
//mod tuples;
// mod array;
//mod vectors;
// mod conditional;
// mod loops;
// mod functions;
// mod pointer_ref;
// mod structs;
// mod enums;
mod cli;
fn main() {
    //print::run();
    //variables::run();
    // types::run();
    // string::run();
    //tuples::run();
    //array::run();
    //vectors::run();
    //conditional::run();
    // loops::run();;    
    // functions::run();
    // pointer_ref::run();
    // structs::run();
    // enums::run();
    cli::run();
}
